"""Versioned L0-audited configuration facts; no model/source code vendoring."""

CATALOG = {'source_commit': '3f2b80df13c17a09e250f2ebe4d4ecdfd4acf269',
 'paper': '2511.06294v3',
 'official_release': {'darcy': {'model': {'linearno_variant': 'conv_temp',
                                          'linearno_rank': 64,
                                          'hidden': 128,
                                          'heads': 8,
                                          'layers': 8,
                                          'ffn_ratio': 1,
                                          'space_dim': 2,
                                          'fun_dim': 1,
                                          'out_dim': 1,
                                          'time_input': False,
                                          'dropout': 0.0,
                                          'activation': 'gelu',
                                          'ref': 8,
                                          'unified_pos': False,
                                          'H': 85,
                                          'W': 85},
                                'training': {'epochs': 500,
                                             'optimizer': 'AdamW',
                                             'lr': 0.001,
                                             'weight_decay': 1e-06,
                                             'batch_size': 4,
                                             'betas': [0.9, 0.999],
                                             'eps': 1e-08,
                                             'gradient_clip': 1.0,
                                             'train_shuffle': True,
                                             'test_batch_size': 1,
                                             'scheduler': 'OneCycleLR',
                                             'scheduler_step': 'one per outer batch',
                                             'optimizer_step': 'one per outer batch',
                                             'validation_cadence': 'every epoch',
                                             'checkpoint_role': 'final',
                                             'selection_split': None,
                                             'selection_metric': None,
                                             'seed_policy': 'local declared seeds [0,1,2]; not author seeds; '
                                                            'release has no active seed control',
                                             'onecycle_defaults': {'pct_start': 0.3,
                                                                   'anneal_strategy': 'cos',
                                                                   'cycle_momentum': True,
                                                                   'base_momentum': 0.85,
                                                                   'max_momentum': 0.95,
                                                                   'div_factor': 25,
                                                                   'final_div_factor': 10000,
                                                                   'three_phase': False},
                                             'scheduler_epochs': 'fixed500 (release)'},
                                'objective': {'kind': 'relative_L2',
                                              'channels': 'all task output channels',
                                              'region': 'all task points',
                                              'space': 'physical (decode before loss if normalized)',
                                              'reduction': 'sum sample-wise flattened ratios per batch; '
                                                           'epoch display divided by ntrain; no epsilon',
                                              'epsilon': 0,
                                              'gradient_weight': 0.1,
                                              'gradient': 'sum dx/dy relative L2; prediction cropped then '
                                                          'zero-padded only for derivative branch; '
                                                          'central_diff zero padding dx=1/85; l2 computed '
                                                          'before crop'},
                                'evaluation': {'prediction_sampling': 'full points',
                                               'field_metric': 'physical sample-wise relative L2',
                                               'field_channels': 'all output channels',
                                               'field_region': 'all points',
                                               'force_metric': None,
                                               'force_input': None,
                                               'split': 'smooth1 first1000 train; smooth2 first200 test',
                                               'aggregation': 'sample arithmetic mean; report each local '
                                                              'seed and mean/std; never best-test seed',
                                               'batch_size': 1,
                                               'selection': 'final checkpoint only',
                                               'normalizer': 'saved train-fit numerical states; no eval '
                                                             'refit'},
                                'data': {'files': ['piececonst_r421_N1024_smooth1.mat:coeff,sol',
                                                   'piececonst_r421_N1024_smooth2.mat:coeff,sol'],
                                         'split': 'smooth1 first1000 train; smooth2 first200 test',
                                         'normalizer': 'input coefficient and output UnitTransformer; fit '
                                                       'train only; output decoded before loss',
                                         'sampling': 'stride5 spatial; 421x421->85x85',
                                         'checksums': None,
                                         'integrity': 'NOT RUN: no real data'}},
                      'elasticity': {'model': {'linearno_variant': 'temp',
                                               'linearno_rank': 64,
                                               'hidden': 128,
                                               'heads': 8,
                                               'layers': 8,
                                               'ffn_ratio': 1,
                                               'space_dim': 2,
                                               'fun_dim': 0,
                                               'out_dim': 1,
                                               'time_input': False,
                                               'dropout': 0.0,
                                               'activation': 'gelu',
                                               'ref': 8,
                                               'unified_pos': False,
                                               'H': 85,
                                               'W': 85},
                                     'training': {'epochs': 500,
                                                  'optimizer': 'AdamW',
                                                  'lr': 0.001,
                                                  'weight_decay': 1e-05,
                                                  'batch_size': 1,
                                                  'betas': [0.9, 0.999],
                                                  'eps': 1e-08,
                                                  'gradient_clip': 1.0,
                                                  'train_shuffle': True,
                                                  'test_batch_size': 1,
                                                  'scheduler': 'CosineAnnealingLR',
                                                  'scheduler_step': 'epoch',
                                                  'optimizer_step': 'one per outer batch',
                                                  'validation_cadence': 'every epoch',
                                                  'checkpoint_role': 'final',
                                                  'selection_split': None,
                                                  'selection_metric': None,
                                                  'seed_policy': 'local declared seeds [0,1,2]; not author '
                                                                 'seeds; release has no active seed control',
                                                  'onecycle_defaults': None,
                                                  'scheduler_epochs': 500},
                                     'objective': {'kind': 'relative_L2',
                                                   'channels': 'all task output channels',
                                                   'region': 'all task points',
                                                   'space': 'physical (decode before loss if normalized)',
                                                   'reduction': 'sum sample-wise flattened ratios per batch; '
                                                                'epoch display divided by ntrain; no epsilon',
                                                   'epsilon': 0},
                                     'evaluation': {'prediction_sampling': 'full points',
                                                    'field_metric': 'physical sample-wise relative L2',
                                                    'field_channels': 'all output channels',
                                                    'field_region': 'all points',
                                                    'force_metric': None,
                                                    'force_input': None,
                                                    'split': 'first1000 train; last200 test',
                                                    'aggregation': 'sample arithmetic mean; report each '
                                                                   'local seed and mean/std; never best-test '
                                                                   'seed',
                                                    'batch_size': 1,
                                                    'selection': 'final checkpoint only',
                                                    'normalizer': 'saved train-fit numerical states; no eval '
                                                                  'refit'},
                                     'data': {'files': ['elasticity/Meshes/Random_UnitCell_XY_10.npy',
                                                        'elasticity/Meshes/Random_UnitCell_sigma_10.npy'],
                                              'split': 'first1000 train; last200 test',
                                              'normalizer': 'output UnitTransformer fit train; decode before '
                                                            'loss',
                                              'sampling': 'all972 unordered points',
                                              'checksums': None,
                                              'integrity': 'NOT RUN: no real data'}},
                      'ns': {'model': {'linearno_variant': 'plain',
                                       'linearno_rank': 32,
                                       'hidden': 256,
                                       'heads': 8,
                                       'layers': 8,
                                       'ffn_ratio': 2,
                                       'space_dim': 2,
                                       'fun_dim': 10,
                                       'out_dim': 1,
                                       'time_input': False,
                                       'dropout': 0.0,
                                       'activation': 'gelu',
                                       'ref': 10,
                                       'unified_pos': True,
                                       'H': 64,
                                       'W': 64},
                             'training': {'epochs': 500,
                                          'optimizer': 'AdamW',
                                          'lr': 0.001,
                                          'weight_decay': 1e-06,
                                          'batch_size': 2,
                                          'betas': [0.9, 0.999],
                                          'eps': 1e-08,
                                          'gradient_clip': None,
                                          'train_shuffle': True,
                                          'test_batch_size': 1,
                                          'scheduler': 'OneCycleLR',
                                          'scheduler_step': 'one per outer batch',
                                          'optimizer_step': 'one per outer batch',
                                          'validation_cadence': 'every epoch',
                                          'checkpoint_role': 'final',
                                          'selection_split': None,
                                          'selection_metric': None,
                                          'seed_policy': 'local declared seeds [0,1,2]; not author seeds; '
                                                         'release has no active seed control',
                                          'onecycle_defaults': {'pct_start': 0.3,
                                                                'anneal_strategy': 'cos',
                                                                'cycle_momentum': True,
                                                                'base_momentum': 0.85,
                                                                'max_momentum': 0.95,
                                                                'div_factor': 25,
                                                                'final_div_factor': 10000,
                                                                'three_phase': False},
                                          'scheduler_epochs': 500},
                             'objective': {'kind': 'relative_L2',
                                           'channels': 'all task output channels',
                                           'region': 'all task points',
                                           'space': 'physical (decode before loss if normalized)',
                                           'reduction': 'sum sample-wise flattened ratios per batch; epoch '
                                                        'display divided by ntrain; no epsilon',
                                           'epsilon': 0,
                                           'time_reduction': 'sum10 step losses for backward; train '
                                                             'feedback=truth; eval feedback=prediction; '
                                                             'display step mean and flattened trajectory '
                                                             'rL2'},
                             'evaluation': {'prediction_sampling': '10-step prediction-fed rollout; same '
                                                                   'ten-frame sliding window',
                                            'field_metric': 'physical sample-wise relative L2',
                                            'field_channels': 'all output channels',
                                            'field_region': 'all points',
                                            'force_metric': None,
                                            'force_input': None,
                                            'split': 'first1000 train; last200 test',
                                            'aggregation': 'sample arithmetic mean; report each local seed '
                                                           'and mean/std; never best-test seed; distinguish '
                                                           'mean step rL2 and flattened full-trajectory rL2',
                                            'batch_size': 1,
                                            'selection': 'final checkpoint only',
                                            'normalizer': 'saved train-fit numerical states; no eval refit'},
                             'data': {'files': ['NavierStokes_V1e-5_N1200_T20/NavierStokes_V1e-5_N1200_T20.mat:u '
                                                '(target fno root)'],
                                      'split': 'first1000 train; last200 test',
                                      'normalizer': 'none',
                                      'sampling': '64x64; 10 input frames->10 future; one frame each model '
                                                  'call',
                                      'checksums': None,
                                      'integrity': 'NOT RUN: no real data'}},
                      'pipe': {'model': {'linearno_variant': 'conv_temp',
                                         'linearno_rank': 64,
                                         'hidden': 128,
                                         'heads': 8,
                                         'layers': 8,
                                         'ffn_ratio': 1,
                                         'space_dim': 2,
                                         'fun_dim': 0,
                                         'out_dim': 1,
                                         'time_input': False,
                                         'dropout': 0.0,
                                         'activation': 'gelu',
                                         'ref': 8,
                                         'unified_pos': False,
                                         'H': 129,
                                         'W': 129},
                               'training': {'epochs': 500,
                                            'optimizer': 'AdamW',
                                            'lr': 0.001,
                                            'weight_decay': 1e-05,
                                            'batch_size': 4,
                                            'betas': [0.9, 0.999],
                                            'eps': 1e-08,
                                            'gradient_clip': 1.0,
                                            'train_shuffle': True,
                                            'test_batch_size': 1,
                                            'scheduler': 'OneCycleLR',
                                            'scheduler_step': 'one per outer batch',
                                            'optimizer_step': 'one per outer batch',
                                            'validation_cadence': 'every epoch',
                                            'checkpoint_role': 'final',
                                            'selection_split': None,
                                            'selection_metric': None,
                                            'seed_policy': 'local declared seeds [0,1,2]; not author seeds; '
                                                           'release has no active seed control',
                                            'onecycle_defaults': {'pct_start': 0.3,
                                                                  'anneal_strategy': 'cos',
                                                                  'cycle_momentum': True,
                                                                  'base_momentum': 0.85,
                                                                  'max_momentum': 0.95,
                                                                  'div_factor': 25,
                                                                  'final_div_factor': 10000,
                                                                  'three_phase': False},
                                            'scheduler_epochs': 500},
                               'objective': {'kind': 'relative_L2',
                                             'channels': 'all task output channels',
                                             'region': 'all task points',
                                             'space': 'physical (decode before loss if normalized)',
                                             'reduction': 'sum sample-wise flattened ratios per batch; epoch '
                                                          'display divided by ntrain; no epsilon',
                                             'epsilon': 0},
                               'evaluation': {'prediction_sampling': 'full points',
                                              'field_metric': 'physical sample-wise relative L2',
                                              'field_channels': 'all output channels',
                                              'field_region': 'all points',
                                              'force_metric': None,
                                              'force_input': None,
                                              'split': 'target first1200 then first1000/last200; release '
                                                       'first1000/last200 of entire file; equivalent only if '
                                                       'length1200',
                                              'aggregation': 'sample arithmetic mean; report each local seed '
                                                             'and mean/std; never best-test seed',
                                              'batch_size': 1,
                                              'selection': 'final checkpoint only',
                                              'normalizer': 'saved train-fit numerical states; no eval '
                                                            'refit'},
                               'data': {'files': ['Pipe_X.npy', 'Pipe_Y.npy', 'Pipe_Q.npy:channel0'],
                                        'split': 'target first1200 then first1000/last200; release '
                                                 'first1000/last200 of entire file; equivalent only if '
                                                 'length1200',
                                        'normalizer': 'input coordinates and output UnitTransformer fit '
                                                      'train; decode output before loss',
                                        'sampling': 'full129x129',
                                        'checksums': None,
                                        'integrity': 'NOT RUN: no real data'}},
                      'plasticity': {'model': {'linearno_variant': 'conv',
                                               'linearno_rank': 64,
                                               'hidden': 128,
                                               'heads': 8,
                                               'layers': 8,
                                               'ffn_ratio': 1,
                                               'space_dim': 2,
                                               'fun_dim': 1,
                                               'out_dim': 4,
                                               'time_input': True,
                                               'dropout': 0.0,
                                               'activation': 'gelu',
                                               'ref': 8,
                                               'unified_pos': False,
                                               'H': 101,
                                               'W': 31},
                                     'training': {'epochs': 500,
                                                  'optimizer': 'AdamW',
                                                  'lr': 0.001,
                                                  'weight_decay': 1e-06,
                                                  'batch_size': 8,
                                                  'betas': [0.9, 0.999],
                                                  'eps': 1e-08,
                                                  'gradient_clip': 1.0,
                                                  'train_shuffle': True,
                                                  'test_batch_size': 1,
                                                  'scheduler': 'OneCycleLR',
                                                  'scheduler_step': 'one per outer batch',
                                                  'optimizer_step': '20 time updates per outer batch',
                                                  'validation_cadence': 'every epoch',
                                                  'checkpoint_role': 'final',
                                                  'selection_split': None,
                                                  'selection_metric': None,
                                                  'seed_policy': 'local declared seeds [0,1,2]; not author '
                                                                 'seeds; release has no active seed control',
                                                  'onecycle_defaults': {'pct_start': 0.3,
                                                                        'anneal_strategy': 'cos',
                                                                        'cycle_momentum': True,
                                                                        'base_momentum': 0.85,
                                                                        'max_momentum': 0.95,
                                                                        'div_factor': 25,
                                                                        'final_div_factor': 10000,
                                                                        'three_phase': False},
                                                  'scheduler_epochs': 500},
                                     'objective': {'kind': 'relative_L2',
                                                   'channels': 'all task output channels',
                                                   'region': 'all task points',
                                                   'space': 'physical (decode before loss if normalized)',
                                                   'reduction': 'sum sample-wise flattened ratios per batch; '
                                                                'epoch display divided by ntrain; no epsilon',
                                                   'epsilon': 0,
                                                   'time_reduction': 'individual time-step '
                                                                     'loss/backward/optimizer20; test mean '
                                                                     'step and full trajectory rL2'},
                                     'evaluation': {'prediction_sampling': '20 separate time-conditioned '
                                                                           'forwards; concatenate original '
                                                                           'time order',
                                                    'field_metric': 'physical sample-wise relative L2',
                                                    'field_channels': 'all output channels',
                                                    'field_region': 'all points',
                                                    'force_metric': None,
                                                    'force_input': None,
                                                    'split': 'first900 train; last80 test of987',
                                                    'aggregation': 'sample arithmetic mean; report each '
                                                                   'local seed and mean/std; never best-test '
                                                                   'seed; distinguish mean step and '
                                                                   'full-trajectory rL2',
                                                    'batch_size': 1,
                                                    'selection': 'final checkpoint only',
                                                    'normalizer': 'saved train-fit numerical states; no eval '
                                                                  'refit'},
                                     'data': {'files': ['plas_N987_T20.mat:input,output'],
                                              'split': 'first900 train; last80 test of987',
                                              'normalizer': 'input force UnitTransformer fit train',
                                              'sampling': '101x31 spatial;20 time queries; per-sample '
                                                          'torch.randperm20 in train collate',
                                              'checksums': None,
                                              'integrity': 'NOT RUN: no real data'}},
                      'airfoil': {'model': {'linearno_variant': 'conv_temp',
                                            'linearno_rank': 64,
                                            'hidden': 128,
                                            'heads': 8,
                                            'layers': 8,
                                            'ffn_ratio': 1,
                                            'space_dim': 2,
                                            'fun_dim': 0,
                                            'out_dim': 1,
                                            'time_input': False,
                                            'dropout': 0.0,
                                            'activation': 'gelu',
                                            'ref': 8,
                                            'unified_pos': False,
                                            'H': 221,
                                            'W': 51},
                                  'training': {'epochs': 500,
                                               'optimizer': 'AdamW',
                                               'lr': 0.001,
                                               'weight_decay': 1e-05,
                                               'batch_size': 4,
                                               'betas': [0.9, 0.999],
                                               'eps': 1e-08,
                                               'gradient_clip': 1.0,
                                               'train_shuffle': True,
                                               'test_batch_size': 1,
                                               'scheduler': 'OneCycleLR',
                                               'scheduler_step': 'one per outer batch',
                                               'optimizer_step': 'one per outer batch',
                                               'validation_cadence': 'ep%10==0 or final',
                                               'checkpoint_role': 'final',
                                               'selection_split': None,
                                               'selection_metric': None,
                                               'seed_policy': 'local declared seeds [0,1,2]; not author '
                                                              'seeds; release has no active seed control',
                                               'onecycle_defaults': {'pct_start': 0.3,
                                                                     'anneal_strategy': 'cos',
                                                                     'cycle_momentum': True,
                                                                     'base_momentum': 0.85,
                                                                     'max_momentum': 0.95,
                                                                     'div_factor': 25,
                                                                     'final_div_factor': 10000,
                                                                     'three_phase': False},
                                               'scheduler_epochs': 500},
                                  'objective': {'kind': 'relative_L2',
                                                'channels': 'all task output channels',
                                                'region': 'all task points',
                                                'space': 'physical (decode before loss if normalized)',
                                                'reduction': 'sum sample-wise flattened ratios per batch; '
                                                             'epoch display divided by ntrain; no epsilon',
                                                'epsilon': 0},
                                  'evaluation': {'prediction_sampling': 'full points',
                                                 'field_metric': 'physical sample-wise relative L2',
                                                 'field_channels': 'all output channels',
                                                 'field_region': 'all points',
                                                 'force_metric': None,
                                                 'force_input': None,
                                                 'split': 'first1000 train; next200 test',
                                                 'aggregation': 'sample arithmetic mean; report each local '
                                                                'seed and mean/std; never best-test seed',
                                                 'batch_size': 1,
                                                 'selection': 'final checkpoint only',
                                                 'normalizer': 'saved train-fit numerical states; no eval '
                                                               'refit'},
                                  'data': {'files': ['NACA_Cylinder_X.npy',
                                                     'NACA_Cylinder_Y.npy',
                                                     'NACA_Cylinder_Q.npy:channel4'],
                                           'split': 'first1000 train; next200 test',
                                           'normalizer': 'none',
                                           'sampling': 'full221x51',
                                           'checksums': None,
                                           'integrity': 'NOT RUN: no real data'}},
                      'car': {'model': {'linearno_variant': 'shapenet',
                                        'linearno_rank': 32,
                                        'hidden': 256,
                                        'heads': 8,
                                        'layers': 8,
                                        'ffn_ratio': 2,
                                        'space_dim': 3,
                                        'fun_dim': 4,
                                        'out_dim': 4,
                                        'time_input': False,
                                        'dropout': 0.0,
                                        'activation': 'gelu',
                                        'ref': 8,
                                        'unified_pos': False,
                                        'H': 85,
                                        'W': 85},
                              'training': {'epochs': 200,
                                           'lr': 0.001,
                                           'optimizer': 'Adam',
                                           'weight_decay': 0,
                                           'batch_size': 1,
                                           'betas': [0.9, 0.999],
                                           'eps': 1e-08,
                                           'gradient_clip': None,
                                           'drop_last': True,
                                           'scheduler': 'OneCycleLR',
                                           'total_steps': '(ntrain//batch+1)*epochs',
                                           'final_div_factor': 1000,
                                           'scheduler_step': 'each optimizer step',
                                           'validation_cadence': 'ep%10==0 or final',
                                           'preprocessed': 1,
                                           'checkpoint_role': 'final',
                                           'seed_policy': 'local [0,1,2]; release uncontrolled'},
                              'objective': {'kind': 'MSE',
                                            'volume_channels': [0, 1, 2],
                                            'surface_channels': [3],
                                            'volume_region': 'all points',
                                            'surface_region': 'surf',
                                            'surface_weight': 0.5,
                                            'space': 'normalized',
                                            'reduction': 'mean points per channel then mean3 velocity '
                                                         'channels; scalar surface pressure mean',
                                            'epsilon': None},
                              'evaluation': {'prediction_sampling': 'full graph single forward; batch1',
                                             'field_metric': {'primary': 'physical rL2 of flattened '
                                                                         'non-surface velocity3 and surface '
                                                                         'pressure',
                                                              'additional_release': 'normalized channel MSE '
                                                                                    'then aggregate RMSE and '
                                                                                    'rescale std'},
                                             'force_metric': 'mean abs(pred-true)/true (release signed '
                                                             'denominator); Spearman over all test samples',
                                             'force_input': 'hxh existing surface velocities; raw/cache '
                                                            'roots and param0 still hardcoded',
                                             'split': 'fold0 full heldout list; get_samples retains '
                                                      'os.listdir order',
                                             'aggregation': 'sample mean; per-member and per-seed axes '
                                                            'separate; final checkpoint; no best seed',
                                             'normalizer': 'saved coef_norm; evaluation must not refit',
                                             'diagnostic_force_input': 'released_bug_volume_velocity+param0 '
                                                                       'explicit diagnostic ONLY'},
                              'data': {'files': ['param0...param8/*/quadpress_smpl.vtk',
                                                 'param0...param8/*/hexvelo_smpl.vtk',
                                                 'preprocessed per sample x/y/pos/surf/edge_index.npy'],
                                       'split': 'fold_id0 heldout param0 (paper789/100); other eight '
                                                'heldouts optional, not paper9fold',
                                       'normalizer': 'all training points '
                                                     'coef_norm(mean_in,std_in,mean_out,std_out),eps1e-8',
                                       'checksums': None,
                                       'integrity': 'NOT RUN'}},
                      'airfrans': {'model': {'linearno_variant': 'airfrans',
                                             'linearno_rank': 32,
                                             'hidden': 256,
                                             'heads': 8,
                                             'layers': 8,
                                             'ffn_ratio': 2,
                                             'space_dim': 7,
                                             'fun_dim': 0,
                                             'out_dim': 4,
                                             'time_input': False,
                                             'dropout': 0.0,
                                             'activation': 'gelu',
                                             'ref': 8,
                                             'unified_pos': True,
                                             'H': None,
                                             'W': None},
                                   'training': {'epochs': 400,
                                                'lr': 0.001,
                                                'optimizer': 'Adam',
                                                'weight_decay': 0,
                                                'batch_size': 1,
                                                'betas': [0.9, 0.999],
                                                'eps': 1e-08,
                                                'gradient_clip': None,
                                                'scheduler': 'OneCycleLR',
                                                'total_steps': '(ntrain//batch+1)*epochs',
                                                'final_div_factor': 10000,
                                                'scheduler_step': 'each optimizer step',
                                                'validation_cadence': 'ep%10==0 or final,20 random '
                                                                      'resamplings',
                                                'subsampling': 32000,
                                                'debug': 0,
                                                'nmodel': 1,
                                                'r': 0.05,
                                                'max_neighbors': 64,
                                                'checkpoint_role': 'final',
                                                'seed_policy': 'local [0,1,2]; release uncontrolled'},
                                   'objective': {'kind': 'MSE',
                                                 'volume_channels': [0, 1, 2, 3],
                                                 'surface_channels': [0, 1, 2, 3],
                                                 'volume_region': '~surf',
                                                 'surface_region': 'surf',
                                                 'surface_weight': 1,
                                                 'space': 'normalized',
                                                 'reduction': 'per-region point mean per channel '
                                                              'then4-channel mean; batch1',
                                                 'epsilon': None},
                                   'evaluation': {'prediction_sampling': 'random32000 subsets until all '
                                                                         'coordinate pairs covered; '
                                                                         'repeated-node prediction mean; '
                                                                         'physical surface velocities/nut '
                                                                         'fixed0',
                                                  'field_metric': {'primary': 'normalized MSE4 channels per '
                                                                              'region',
                                                                   'secondary': 'physical pressure rL2 as '
                                                                                'separately labelled audit '
                                                                                'metric'},
                                                  'field_region': ['~surf', 'surf'],
                                                  'force_metric': 'per-sample '
                                                                  'abs((Ctrue-Cpred)/Ctrue),testmean; C_L '
                                                                  'Spearman all test',
                                                  'force_input': 'full scattered predicted velocity and '
                                                                 'pressure; VTK derivatives/normals/length '
                                                                 'integration; same boundary fixing and '
                                                                 'rotation',
                                                  'split': 'entire manifest full_test; n_test3 only chooses '
                                                           'exports',
                                                  'aggregation': 'sample metrics then member mean/std; seed '
                                                                 'mean/std kept separate; prediction '
                                                                 'ensemble not silently substituted',
                                                  'normalizer': 'saved train-fit coef_norm; no eval refit'},
                                   'data': {'files': ['Dataset/manifest.json',
                                                      'Dataset/<simulation>/<simulation>_internal.vtu',
                                                      'Dataset/<simulation>/<simulation>_aerofoil.vtp'],
                                            'split': 'full_train '
                                                     'last10%validation;720train80val200full_test; scarce '
                                                     'uses full_test, aoa/reynolds separate',
                                            'normalizer': 'coef_norm fit train only,eps1e-8; x normalized '
                                                          'but pos raw',
                                            'checksums': None,
                                            'integrity': 'NOT RUN',
                                            'sdf_source': 'VTK internal.point_data[implicit_distance] with '
                                                          'sign inversion'}}},
 'overrides': {'paper_table8_on_release_model': {'darcy': {'training': {},
                                                           'objective': {},
                                                           'evaluation': {},
                                                           'data': {},
                                                           'model': {}},
                                                 'elasticity': {'training': {},
                                                                'objective': {},
                                                                'evaluation': {},
                                                                'data': {},
                                                                'model': {}},
                                                 'ns': {'training': {},
                                                        'objective': {},
                                                        'evaluation': {},
                                                        'data': {},
                                                        'model': {}},
                                                 'pipe': {'training': {},
                                                          'objective': {},
                                                          'evaluation': {},
                                                          'data': {},
                                                          'model': {}},
                                                 'plasticity': {'training': {},
                                                                'objective': {},
                                                                'evaluation': {},
                                                                'data': {},
                                                                'model': {}},
                                                 'airfoil': {'training': {},
                                                             'objective': {},
                                                             'evaluation': {},
                                                             'data': {},
                                                             'model': {}},
                                                 'car': {'training': {},
                                                         'objective': {'kind': 'relative_L2',
                                                                       'volume_region': '~surf',
                                                                       'surface_weight': 1,
                                                                       'space': 'UNRESOLVED: physical vs '
                                                                                'normalized training rL2',
                                                                       'reduction': 'UNRESOLVED: '
                                                                                    'concatenate3 velocity '
                                                                                    'channels vs channelwise '
                                                                                    'ratios then mean; '
                                                                                    'sample mean',
                                                                       'epsilon': 0},
                                                         'evaluation': {},
                                                         'data': {},
                                                         'model': {}},
                                                 'airfrans': {'training': {},
                                                              'objective': {'kind': 'relative_L2',
                                                                            'volume_channels': 'UNRESOLVED: '
                                                                                               'all4 vs '
                                                                                               'pressure-only '
                                                                                               '(paper '
                                                                                               'evaluation '
                                                                                               'pressure-only '
                                                                                               'is explicit)',
                                                                            'surface_channels': 'UNRESOLVED: '
                                                                                                'all4 vs '
                                                                                                'pressure-only',
                                                                            'surface_weight': 0.5,
                                                                            'space': 'UNRESOLVED: physical '
                                                                                     'vs normalized training '
                                                                                     'rL2',
                                                                            'reduction': 'UNRESOLVED: '
                                                                                         'channelwise mean '
                                                                                         'vs combined '
                                                                                         'per-sample norm',
                                                                            'epsilon': 0},
                                                              'evaluation': {'field_metric': {'primary': 'physical '
                                                                                                         'pressure '
                                                                                                         'channel2 '
                                                                                                         'rL2',
                                                                                              'secondary': 'release '
                                                                                                           'normalized '
                                                                                                           'MSE4 '
                                                                                                           'channels'}},
                                                              'data': {},
                                                              'model': {}}},
               'transolver_matched': {'darcy': {'training': {'weight_decay': 1e-05,
                                                             'gradient_clip': 0.1,
                                                             'test_batch_size': 4,
                                                             'validation_cadence': 'current target every '
                                                                                   'epoch',
                                                             'scheduler_epochs': 500},
                                                'objective': {},
                                                'evaluation': {},
                                                'data': {},
                                                'model': {'unified_pos': True}},
                                      'elasticity': {'training': {'gradient_clip': 0.1,
                                                                  'validation_cadence': 'current target '
                                                                                        'every epoch'},
                                                     'objective': {},
                                                     'evaluation': {},
                                                     'data': {},
                                                     'model': {}},
                                      'ns': {'training': {'weight_decay': 1e-05,
                                                          'test_batch_size': 2,
                                                          'validation_cadence': 'current target every epoch'},
                                             'objective': {},
                                             'evaluation': {},
                                             'data': {},
                                             'model': {'ffn_ratio': 1, 'ref': 8}},
                                      'pipe': {'training': {'batch_size': 8,
                                                            'gradient_clip': 0.1,
                                                            'test_batch_size': 8,
                                                            'validation_cadence': 'current target every '
                                                                                  'epoch'},
                                               'objective': {},
                                               'evaluation': {},
                                               'data': {},
                                               'model': {'ffn_ratio': 2}},
                                      'plasticity': {'training': {'weight_decay': 1e-05,
                                                                  'gradient_clip': 0.1,
                                                                  'test_batch_size': 8,
                                                                  'validation_cadence': 'current target '
                                                                                        'every epoch'},
                                                     'objective': {},
                                                     'evaluation': {},
                                                     'data': {},
                                                     'model': {}},
                                      'airfoil': {'training': {'gradient_clip': 0.1,
                                                               'test_batch_size': 4,
                                                               'validation_cadence': 'current target every '
                                                                                     'epoch'},
                                                  'objective': {},
                                                  'evaluation': {},
                                                  'data': {},
                                                  'model': {}},
                                      'car': {'training': {},
                                              'objective': {},
                                              'evaluation': {},
                                              'data': {},
                                              'model': {}},
                                      'airfrans': {'training': {'epochs': 398},
                                                   'objective': {},
                                                   'evaluation': {},
                                                   'data': {},
                                                   'model': {}}}}}
